#!/bin/bash

REVERSE_SSH_PORT=2000

SCRIPT_DIR="$(readlink -f $(dirname $0))"

while [ 1 ]
do
	ssh -o StrictHostKeyChecking=no -p 2222 -i "$SCRIPT_DIR/config/jig_id" -nNR $REVERSE_SSH_PORT:localhost:22 jig@testjig.hopto.org &> /dev/null
	sleep 60
	# Assume we failed to connect, so increment
	let REVERSE_SSH_PORT='REVERSE_SSH_PORT + 1'
	if [ "$REVERSE_SSH_PORT" -ge "3000" ] ; then
		REVERSE_SSH_PORT=2000
	fi
done

