#!/bin/bash

SCRIPT_DIR="$(readlink -f $(dirname $0))"
source $SCRIPT_DIR/test_util.sh

TEST_NAME="TEST_ADDON_CONNECTOR"

TEST_ID="04"
SHORT_DESC="Test BANK26 loopback IO_L9P_AD3P <-> IO_L10P_AD2P"
CMD="sudo \$SCRIPT_DIR/export_gpios.sh;"
CMD+="echo 1 > /sys/class/gpio/gpio460/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio462/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio460/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="05"
SHORT_DESC="Test BANK26 loopback IO_L9N_AD3N <-> IO_L10N_AD2N"
CMD="echo 1 > /sys/class/gpio/gpio461/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio463/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio461/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="06"
SHORT_DESC="Test BANK26 loopback IO_L11P_AD1P <-> IO_L12P_AD0P"
CMD="echo 1 > /sys/class/gpio/gpio464/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio466/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio464/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="07"
SHORT_DESC="Test BANK26 loopback IO_L11N_AD1N <-> IO_L12N_AD0N"
CMD="echo 1 > /sys/class/gpio/gpio465/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio467/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio465/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="08"
SHORT_DESC="Test BANK64 loopback IO_L1P_T0L_N0_DBC <-> IO_L2P_T0L_N2"
CMD="echo 1 > /sys/class/gpio/gpio475/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio469/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio475/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="09"
SHORT_DESC="Test BANK64 loopback IO_L1N_T0L_N1_DBC <-> IO_L2N_T0L_N3"
CMD="echo 1 > /sys/class/gpio/gpio468/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio470/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio468/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="10"
SHORT_DESC="Test BANK64 loopback IO_L21P_T3L_N4_AD8P <-> IO_L23P_T3U_N8"
CMD="echo 1 > /sys/class/gpio/gpio471/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio473/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio471/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="11"
SHORT_DESC="Test BANK64 loopback IO_L21N_T3L_N5_AD8N <-> IO_L23N_T3U_N9"
CMD="echo 1 > /sys/class/gpio/gpio472/value;"
CMD+="LOOP=\$(cat /sys/class/gpio/gpio474/value) ;"
CMD+="echo 0 > /sys/class/gpio/gpio472/value;"
CMD+="[[ \$LOOP -eq 1 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="12"
SHORT_DESC="Test AUXADC0 when AUXDAC0=0,05V"
CMD="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage2_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 220 ]] && [[ \$AUXADC -le 290 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="13"
SHORT_DESC="Test AUXADC0 when AUXDAC0=1V"
CMD="echo 1000 > /sys/bus/iio/devices/iio\:device1/out_voltage2_input;"
CMD+="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage2_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 660 ]] && [[ \$AUXADC -le 750 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="14"
SHORT_DESC="Test AUXADC1 when AUXDAC1=0,05V"
CMD="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage3_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 240 ]] && [[ \$AUXADC -le 300 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="15"
SHORT_DESC="Test AUXADC1 when AUXDAC1=1V"
CMD="echo 1000 > /sys/bus/iio/devices/iio\:device1/out_voltage3_input;"
CMD+="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage3_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 660 ]] && [[ \$AUXADC -le 750 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="16"
SHORT_DESC="Test AUXADC2 when AUXDAC2=0,05V"
CMD="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage4_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 220 ]] && [[ \$AUXADC -le 280 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="17"
SHORT_DESC="Test AUXADC2 when AUXDAC2=1V"
CMD="echo 1000 > /sys/bus/iio/devices/iio\:device1/out_voltage4_input;"
CMD+="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage4_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 620 ]] && [[ \$AUXADC -le 700 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="16"
SHORT_DESC="Test AUXADC3 when AUXDAC3=0,05V"
CMD="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage5_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 220 ]] && [[ \$AUXADC -le 280 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="17"
SHORT_DESC="Test AUXADC3 when AUXDAC3=1V"
CMD="echo 1000 > /sys/bus/iio/devices/iio\:device1/out_voltage5_input;"
CMD+="AUXADC=\$(cat /sys/bus/iio/devices/iio\:device1/in_voltage5_input);"
CMD+="echo \$AUXADC;"
CMD+="[[ \$AUXADC -ge 620 ]] && [[ \$AUXADC -le 700 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

return $FAIL_COUNT
