#!/bin/bash

SCRIPT_DIR="$(readlink -f $(dirname $0))"

source $SCRIPT_DIR/test_util.sh

TEST_NAME="TEST_MEASURE_POWER"

TEST_ID="01"
SHORT_DESC="Test VCC INT value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage0_vccint_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage0_vccint_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 810 ]] && [[ \$VAL -le 892 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="02"
SHORT_DESC="Test VCC AUX value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage1_vccaux_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage1_vccaux_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 1710 ]] && [[ \$VAL -le 1890 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="03"
SHORT_DESC="Test VCC BRAM value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage2_vccbram_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage2_vccbram_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 810 ]] && [[ \$VAL -le 892 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="04"
SHORT_DESC="Test VCC_PS_INTLP value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage3_vccpsintlp_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage3_vccpsintlp_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 810 ]] && [[ \$VAL -le 892 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="05"
SHORT_DESC="Test VCC_PS_INTFP value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage4_vccpsintfp_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage4_vccpsintfp_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 810 ]] && [[ \$VAL -le 892 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="06"
SHORT_DESC="Test VCC PS AUX value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage5_vccpsaux_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage5_vccpsaux_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 1710 ]] && [[ \$VAL -le 1890 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="07"
SHORT_DESC="Test 1V2_PS_DDR4 value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage9_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage9_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 1100 ]] && [[ \$VAL -le 1300 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="08"
SHORT_DESC="Test 2V5."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage10_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage10_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*3}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 2400 ]] && [[ \$VAL -le 2600 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="09"
SHORT_DESC="Test 1V3_RF value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage11_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage11_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 1200 ]] && [[ \$VAL -le 1400 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="10"
SHORT_DESC="Test 1V0_RF value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage12_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage12_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 950 ]] && [[ \$VAL -le 1100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="11"
SHORT_DESC="Test 1V8_MGTRAVCC value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage13_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage13_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 1710 ]] && [[ \$VAL -le 1890 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="12"
SHORT_DESC="Test 1V3_PS_DDR4 value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage14_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage14_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 1140 ]] && [[ \$VAL -le 1260 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="13"
SHORT_DESC="Test 5V0."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage15_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage15_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*6.743}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 4800 ]] && [[ \$VAL -le 5200 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="14"
SHORT_DESC="Test 0V85_MGTRAVCC value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage16_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage16_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 830 ]] && [[ \$VAL -le 860 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="15"
SHORT_DESC="Test VTT_PS_DDR4 value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage17_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage17_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 570 ]] && [[ \$VAL -le 630 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="16"
SHORT_DESC="Test 5V0_RF value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage18_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage18_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*6.743}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 4800 ]] && [[ \$VAL -le 5200 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="17"
SHORT_DESC="Test 1V8_RF value."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage19_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage19_scale);"
CMD+="VAL=\$(echo \$RVAL \$SCALE | awk '{printf \"%4.0f\n\",\$1*\$2*2}');"
CMD+="echo \" \$VAL mV \";"
CMD+="[[ \$VAL -ge 1710 ]] && [[ \$VAL -le 1890 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

exit $FAIL_COUNT
