#!/bin/bash

SCRIPT_DIR="$(readlink -f $(dirname $0))"

source $SCRIPT_DIR/test_util.sh

TEST_NAME="TEST_MEASURE_POWER"

TEST_ID="01"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage0_pspll_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage0_pspll_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="02"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage1_vcc_psbatt_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage1_vcc_psbatt_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="03"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage2_vccint_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage2_vccint_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="04"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage3_vccbram_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage3_vccbram_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="05"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage4_vccaux_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage4_vccaux_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="06"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage5_vcc_psddrpll_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage5_vcc_psddrpll_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="07"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage6_vccpsintfpddr_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage6_vccpsintfpddr_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="08"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage7_vccpsintlp_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage7_vccpsintlp_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="09"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage8_vccpsintfp_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage8_vccpsintfp_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="10"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage9_vccpsaux_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage9_vccpsaux_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="11"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage10_vccpsddr_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage10_vccpsddr_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="12"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage11_vccpsio3_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage11_vccpsio3_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="13"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage12_vccpsio0_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage12_vccpsio0_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="14"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage13_vccpsio1_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage13_vccpsio1_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="15"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage14_vccpsio2_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage14_vccpsio2_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="16"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage15_psmgtravcc_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage15_psmgtravcc_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="17"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage16_psmgtravtt_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage16_psmgtravtt_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="18"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage17_vccams_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage17_vccams_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="19"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage18_vccint_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage18_vccint_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="20"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage19_vccaux_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage19_vccaux_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="21"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage20_vccvrefp_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage20_vccvrefp_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="22"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage21_vccvrefn_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage21_vccvrefn_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="23"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage22_vccbram_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage22_vccbram_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="24"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage23_vccplintlp_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage23_vccplintlp_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="25"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage24_vccplintfp_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage24_vccplintfp_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="26"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage25_vccplaux_raw);"
CMD+="SCALE=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage25_vccplaux_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"

TEST_ID="27"
SHORT_DESC="Test X."
CMD="RVAL=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage26_vccams_raw);"
CMD+="scale=\$(cat /sys/bus/iio/devices/iio:device0/in_voltage26_vccams_scale);"
CMD+="[[ \$VAL -ge 5500 ]] && [[ \$VAL -le 6100 ]]"
run_test $TEST_ID "$SHORT_DESC" "$CMD"
